
package com.iaewtpi.reservasWsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWCFReservaVehiculos", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWCFReservaVehiculos {


    /**
     * 
     * @param consultarVehiculosRequest
     * @return
     *     returns com.iaewtpi.reservasWsdl.ConsultarVehiculosDisponiblesResponse2
     * @throws IWCFReservaVehiculosConsultarVehiculosDisponiblesStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultarVehiculosDisponibles", action = "http://tempuri.org/IWCFReservaVehiculos/ConsultarVehiculosDisponibles")
    @WebResult(name = "ConsultarVehiculosDisponiblesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarVehiculosDisponibles", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.ConsultarVehiculosDisponibles")
    @ResponseWrapper(localName = "ConsultarVehiculosDisponiblesResponse", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.ConsultarVehiculosDisponiblesResponse")
    public ConsultarVehiculosDisponiblesResponse2 consultarVehiculosDisponibles(
        @WebParam(name = "ConsultarVehiculosRequest", targetNamespace = "http://tempuri.org/")
        ConsultarVehiculosRequest consultarVehiculosRequest)
        throws IWCFReservaVehiculosConsultarVehiculosDisponiblesStatusResponseFaultFaultMessage
    ;

    /**
     * 
     * @param reservarVehiculoRequest
     * @return
     *     returns com.iaewtpi.reservasWsdl.ReservarVehiculoResponse2
     * @throws IWCFReservaVehiculosReservarVehiculoStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "ReservarVehiculo", action = "http://tempuri.org/IWCFReservaVehiculos/ReservarVehiculo")
    @WebResult(name = "ReservarVehiculoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReservarVehiculo", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.ReservarVehiculo")
    @ResponseWrapper(localName = "ReservarVehiculoResponse", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.ReservarVehiculoResponse")
    public ReservarVehiculoResponse2 reservarVehiculo(
        @WebParam(name = "ReservarVehiculoRequest", targetNamespace = "http://tempuri.org/")
        ReservarVehiculoRequest reservarVehiculoRequest)
        throws IWCFReservaVehiculosReservarVehiculoStatusResponseFaultFaultMessage
    ;

    /**
     * 
     * @param consultarReservasRequest
     * @return
     *     returns com.iaewtpi.reservasWsdl.ConsultarReservasResponse2
     * @throws IWCFReservaVehiculosConsultarReservasStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultarReservas", action = "http://tempuri.org/IWCFReservaVehiculos/ConsultarReservas")
    @WebResult(name = "ConsultarReservasResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarReservas", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.ConsultarReservas")
    @ResponseWrapper(localName = "ConsultarReservasResponse", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.ConsultarReservasResponse")
    public ConsultarReservasResponse2 consultarReservas(
        @WebParam(name = "ConsultarReservasRequest", targetNamespace = "http://tempuri.org/")
        ConsultarReservasRequest consultarReservasRequest)
        throws IWCFReservaVehiculosConsultarReservasStatusResponseFaultFaultMessage
    ;

    /**
     * 
     * @param cancelarReservaRequest
     * @return
     *     returns com.iaewtpi.reservasWsdl.CancelarReservaResponse2
     * @throws IWCFReservaVehiculosCancelarReservaStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "CancelarReserva", action = "http://tempuri.org/IWCFReservaVehiculos/CancelarReserva")
    @WebResult(name = "CancelarReservaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelarReserva", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.CancelarReserva")
    @ResponseWrapper(localName = "CancelarReservaResponse", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.CancelarReservaResponse")
    public CancelarReservaResponse2 cancelarReserva(
        @WebParam(name = "CancelarReservaRequest", targetNamespace = "http://tempuri.org/")
        CancelarReservaRequest cancelarReservaRequest)
        throws IWCFReservaVehiculosCancelarReservaStatusResponseFaultFaultMessage
    ;

    /**
     * 
     * @param consultarCiudadesRequest
     * @return
     *     returns com.iaewtpi.reservasWsdl.ConsultarCiudadesResponse2
     * @throws IWCFReservaVehiculosConsultarCiudadesStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultarCiudades", action = "http://tempuri.org/IWCFReservaVehiculos/ConsultarCiudades")
    @WebResult(name = "ConsultarCiudadesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarCiudades", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.ConsultarCiudades")
    @ResponseWrapper(localName = "ConsultarCiudadesResponse", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.ConsultarCiudadesResponse")
    public ConsultarCiudadesResponse2 consultarCiudades(
        @WebParam(name = "ConsultarCiudadesRequest", targetNamespace = "http://tempuri.org/")
        ConsultarCiudadesRequest consultarCiudadesRequest)
        throws IWCFReservaVehiculosConsultarCiudadesStatusResponseFaultFaultMessage
    ;

    /**
     * 
     * @return
     *     returns com.iaewtpi.reservasWsdl.ConsultarPaisesResponse2
     * @throws IWCFReservaVehiculosConsultarPaisesStatusResponseFaultFaultMessage
     */
    @WebMethod(operationName = "ConsultarPaises", action = "http://tempuri.org/IWCFReservaVehiculos/ConsultarPaises")
    @WebResult(name = "ConsultarPaisesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarPaises", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.ConsultarPaises")
    @ResponseWrapper(localName = "ConsultarPaisesResponse", targetNamespace = "http://tempuri.org/", className = "com.iaewtpi.reservasWsdl.ConsultarPaisesResponse")
    public ConsultarPaisesResponse2 consultarPaises()
        throws IWCFReservaVehiculosConsultarPaisesStatusResponseFaultFaultMessage
    ;

}
